<?php

$cfg = array(

    'db' => array(
        'adwords' => array(
            'host' => '%db_host%',
            'user' => '%db_user%',
            'pass' => '%db_password%',
            'name' => 'adwords'
        ),
        'common' => array(
            'host' => '%db_host%',
            'user' => '%db_user%',
            'pass' => '%db_password%',
            'name' => 'common'
        ),
        'api' => array(
            'host' => '%db_host%',
            'user' => '%db_user%',
            'pass' => '%db_password%',
            'name' => 'runashop_api'
        ),
        'priceportal' => array(
            'host' => '%db_host%',
            'user' => '%db_user%',
            'pass' => '%db_password%',
            'name' => 'runashop_priceportal'
        ),
        'bing' => array(
            'host' => '%db_host%',
            'user' => '%db_user%',
            'pass' => '%db_password%',
            'name' => 'bing'
        ),
        'stats' => array(
            'host' => '%db_host%',
            'user' => '%db_user%',
            'pass' => '%db_password%',
            'name' => 'stats'
        ),
    ),

    'host' => '%host%',
    'rpl_host' => "%rpl_host%",

    'emailsFromAddress' => 'noreply@runashop.com',

    'errorHook' => true,
    'errorEmails' => array(
        '%email%' => '%name%'
    ),

    'reportsDir' => __DIR__ . '/tmp',

);